package cn.ctwsm.gdpi.cmd;

public class SQL {
    //Commons SQL
    public static final String CHECK_TABLE_SQL = "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = '%s'";

    //for imei data table
    public static final String CREATE_IMEI_DATA_TABLE_SQL = "CREATE TABLE %s (ACCOUNT VARCHAR2(255), VISIT_TIME VARCHAR2(14), IMEI VARCHAR2(15))";
    public static final String INSERT_IMEI_DATA_SQL = "INSERT INTO %s (ACCOUNT, VISIT_TIME, IMEI) VALUES (?, ?, ?)";

    //for task table
    public static final String CREATE_TASK_TABLE_SQL = "CREATE TABLE %s (ID VARCHAR2(36), FILE_SIZE NUMBER, FILE_COUNT NUMBER, PROCESS_MILLS NUMBER, BEGIN_TIME DATE, SUCCESS NUMBER)";
    public static final String INSERT_TASK_TABLE_SQL = "INSERT INTO %s (ID, FILE_SIZE, FILE_COUNT, PROCESS_MILLS, BEGIN_TIME, SUCCESS) VALUES (?, ?, ?, ?, ?, ?)";

    //for job table
    public static final String CREATE_JOB_TABLE_SQL = "CREATE TABLE %s (ID VARCHAR2(36), TASK_ID VARCHAR2(36), FILE_NAME VARCHAR2(255), FILE_SIZE NUMBER, SOURCE_RECORD_COUNT NUMBER, RESULT_COUNT NUMBER, PROCESS_MILLS NUMBER, INSERT_MILLS  NUMBER, BEGIN_TIME DATE, SUCCESS NUMBER)";
    public static final String INSERT_JOB_TABLE_SQL = "INSERT INTO %s (ID, TASK_ID, FILE_NAME, FILE_SIZE, SOURCE_RECORD_COUNT, RESULT_COUNT, PROCESS_MILLS, INSERT_MILLS, BEGIN_TIME, SUCCESS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    //for mdn data table
    public static final String CREATE_MSISDN_DATA_TABLE_SQL = "CREATE TABLE %s (ACCOUNT VARCHAR2(255), VISIT_TIME VARCHAR2(14), MSISDN VARCHAR2(15), MODEL VARCHAR2(255))";
    public static final String INSERT_MSISDN_DATA_SQL = "INSERT INTO %s (ACCOUNT, VISIT_TIME, MSISDN, MODEL) VALUES (?, ?, ?, ?)";

}
